config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  get 'locations', to: "welcome#locations"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def locations
    @locations =  (OpenRegister.register('country', :beta)._all_records.reject{ |r| r.end_date.present? } +
                  OpenRegister.register('territory', :beta)._all_records.reject{ |r| r.end_date.present? }).sort_by(&:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
- content_for :page_title, ' - GOV.UK Country Register'

- content_for :inside_header do
  %h1.header-title Country Registers

- content_for :homepage_url, "/"

- content_for :head do
  = stylesheet_link_tag 'application'
  = stylesheet_link_tag '//unpkg.com/accessible-typeahead@0.4.0/examples/styled.css'
  = csrf_meta_tags
  = javascript_include_tag "//unpkg.com/accessible-typeahead@0.4.0"

- content_for :content do
  %main{role:'main'}
    = content_for?(:main) ? yield(:main) : yield

- content_for :body_end do
  = javascript_include_tag 'application'
  = yield(:javascript)

= render file: 'layouts/govuk_template'

app/views/welcome/home.html.haml
= content_for :page_title, 'Home'
= content_for :body_classes, 'home-page'

.masthead.product-page-section
  .container
    .grid-row
      .column-two-thirds
        %h1.heading-xlarge An accurate list of locations you can trust
        %p Access authoritative open government country and territory data in one place, to use anywhere
        = link_to "View the data", locations_path, class: "button button-start"
      .column-one-third
        = image_tag "registers-illustration.png", alt: "Illustration of the cocept of registers", class: "hide-for-small"

.container
  .product-page-section
    .grid-row
      .column-one-half
        %h2.heading-large Using government data is challenging
        %ul.bulleted-list
          %li Government data is hard to find, use and share
          %li There are duplicates that lead to confusion
          %li The data sources are not reliable
      .column-one-half
        = image_tag "excel-screenshot.png", class: "image-with-border"

  .product-page-section
    .grid-row
      .column-one-half
        %h2.heading-large Location registers can solve these problems
        %ul.bulleted-list
          %li Lists of information available to everyone
          %li One single source of information provided by government organisations
          %li A stable solution that you can rely on for your service
      .column-one-half
        = image_tag "location-table-screenshot.png", class: "image-with-border"

  .product-page-section
    .grid-row
      %h2.heading-large.section-header Who is using Location registers
      .column-two-thirds
        %blockquote
          %p As a high profile site, #{link_to "https://petition.parliament.uk"} needs to be accurate and up-to-date wherever possible. So when we were given the chance to remove one more static set of data with an API we jumped at the chance. This is because having an authoritative list that updates automatically eliminates a huge amount of effort when validating data. We were able to identity a number of places where we had used the wrong country name previously.
          %cite Andrew White, UK Government and Parliamnent Petitions
        %p= link_to "Read the full case study", "#"
      .column-one-third
        = image_tag "petitions-logo.jpg", width: 250, class: "image-right";

  .product-page-section
    .grid-row
      .column-one-half
        %h2.heading-large Location data ready to use
        %p We’ve built a location picker that uses the #{link_to "Country", "https://country.register.gov.uk/", target: :blank} and #{link_to "Territory", "https://territory.register.gov.uk/", target: :blank} registers. With this picker, the users of your service will be able to provide information using authoritative and reliable data.
        %p
          = link_to "Find more about our location picker", "https://designnotes.blog.gov.uk/2017/04/20/were-building-an-autocomplete/", target: :blank
      .column-one-half
        = image_tag "picker.gif", alt: "A demo of how register data can work on a form", class: "image-with-border"

  .product-page-section
    .grid-row
      .column-full
        %h2.heading-large.section-header.centered Organisations creating Registers
        %ul.org-logos
          %li= image_tag "Home_Office.svg", class: "logo home-office"
          %li= image_tag "1280px-Foreign_and_Commonwealth_Office_Logo.svg.png", class: "logo fco"
          %li= image_tag "Department_for_Work_and_Pensions_logo.svg", class: "logo dwp"
          %li= image_tag "Department_for_Education.svg", class: "logo education"
          %li= image_tag "Ministry_of_Justice_logo.svg", class: "logo moj"
          %li= image_tag "Department_for_Communities_and_Local_Government_logo.svg", class: "logo local-government"


  .product-page-section
    .grid-row
      .column-one-half
        %h2.heading-large Get in touch
        %p
          = link_to "Contact the team", "https://registers.cloudapps.digital/support"
          if you have any questions about using GOV.UK Registers or integrating it with your service.
        %p GOV.UK Registers is built and supported by a full time team at the Government Digital Service.
      .column-one-half
        = image_tag "registers-team.png", alt: "Video to learn how to integrate registers in your service"

app/views/welcome/locations.html.haml
= content_for :page_title, 'Locations'

.container
  = link_to "Back", root_path, class: "link-back"

  .grid-row
    .column-two-thirds
      %h1.heading-xlarge Location Registers

      %form.filter-locations
        %h2.heading-medium Filter this data
        .grid-row
          .column-one-half
            %fieldset
              %legend Type of location
              .multiple-choice
                %input#location-type-1{name: "location-types", type: "checkbox", value: "location-countries", checked: true}
                %label{for: "location-type-1"} Countries
              .multiple-choice
                %input#location-type-2{name: "location-types", type: "checkbox", value: "location-territories", checked: true}
                %label{for: "location-type-2"} Territories
          .column-one-half
            %fieldset
              %legend Status of location
              .multiple-choice
                %input#location-type-3{name: "location-types", type: "checkbox", value: "location-active", checked: true}
                %label{for: "location-type-3"} Active
              .multiple-choice
                %input#location-type-3{name: "location-types", type: "checkbox", value: "location-inactive"}
                %label{for: "location-type-3"} Inactive
        %button.button Filter

      %h2.heading-large #{@locations.count} Locations found

      = form_for root_path do |f|
        %h3.heading-medium View results on a location picker
        .form-group
          %label.form-label-bold.visually-hidden Select location
          = f.select "locations", @locations.map(&:name), {}, id: "country_select", class: "form-control"

    .column-one-third
      %h3.heading-medium About the registers
      %h4.heading-small Custodian
      %p Tony Worron
      %h4.heading-small Managed by
      = image_tag "1280px-Foreign_and_Commonwealth_Office_Logo.svg.png", width: 125
      %h4.heading-small Last updated
      %p 29 March 2017
      %ul
        %li= link_to "Download this data", "https://country.register.gov.uk/download", target: :blank
        %li= link_to "Use this data in your service", "https://registers.cloudapps.digital/using-registers", target: :blank

  .grid-row
    .column-two-thirds
      %h3.heading-medium View results on a table
      %details{:role => "group"}
        %summary{"aria-controls" => "details-content-0", "aria-expanded" => "false", :role => "button"}
          %span.summary What are the table headers?
        #details-content-0.panel.panel-border-narrow{"aria-hidden" => "true"}
          %dl
            %dt Key:
            %dd The location's 2-letter ISO 3166-2 alpha2 code
            %dt Name:
            %dd The commonly-used name of a location
            %dt Official name:
            %dd The official or technical name of a location
            %dt Citizen names:
            %dd The name of a location's citizens
            %dt Start-date
            %dd The date a record first became relevant to a register. For example, the date a country was first recognised by the UK
            %dt End date:
            %dd The date a record stopped being applicable. For example, the date a school closed down
  .grid-row
    .column-full
      %table
        %colgroup
          %col{width: '10%'}
          %col{width: '20%'}
          %col{width: '25%'}
          %col{width: '30%'}
          %col{width: '15%'}
        %thead
          %tr
            %th Key
            %th Name
            %th Official name
            %th Citizen name
            %th Start date
        %tbody
          - @locations.each do |location|
            %tr
              %td= location.key
              %td= location.name
              %td= location.official_name
              %td= location.try(:citizen_names)
              %td= location.start_date

= content_for :javascript do
  :javascript
    $(document).ready(function() {
      element = document.querySelector('#country_select')
      AccessibleTypeahead.enhanceSelectElement({
        selectElement: element,
        placeholder: "Search for a location"
      })
    });